wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1638389274
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 3
      - 8
      4: 3.7.12
      5: 0.12.7
      8:
      - 5
